
version: "3.9"
services:

  tinyproxy:
    image: vimagick/tinyproxy
    networks:
      - no-internet
      - internet
    volumes:
      - ./config/tinyproxy.conf:/etc/tinyproxy/tinyproxy.conf
    restart: unless-stopped

  jbang:
    image: jbangdev/jbang-action
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
    environment:
      - http_proxy=http://tinyproxy:8888
      - https_proxy=http://tinyproxy:8888
    networks:
      - no-internet
    volumes:
      - ../../build/install/jbang/bin:/jbang/bin:ro
      - ../../itests:/itests:ro
      - ./config/settings.xml:/root/.m2/settings.xml
    working_dir: /itests

networks:
  internet: {}
  no-internet:
    internal: true

