name: Shared Build Setup
description: Setup the build environment for the shared build commands

inputs:
  add-job-summary:
    description: Add the job summary to the output
    required: false
    default: 'always'
  java-version:
    description: The Java version to use
    required: false
    default: '11'
outputs:
  github-short-sha:
    description: The short github.sha
    value: ${{ steps.git-short-sha.outputs.github-short-sha }}
runs:
  using: 'composite'
  steps:
    - name: Set short git commit SHA
      shell: bash
      id: git-short-sha
      run: |
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "github-short-sha=$calculatedSha" >> $GITHUB_OUTPUT
    - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5
      with:
        java-version: ${{ inputs.java-version }}
        distribution: temurin
    - name: setup-gradle
      uses: gradle/actions/setup-gradle@748248ddd2a24f49513d8f472f81c3a07d4d50e1 # v4
      with:
          cache-overwrite-existing: true
          add-job-summary: ${{ inputs.add-job-summary }}
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@c0afd6f790e3a5564914980036ebf83216678101 # v3
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
      with:
        limit-access-to-actor: true
        detached: ${{ github.event.inputs.debug_detached }}