name: Shared Build Setup
description: Setup the build environment for the shared build commands

inputs:
  add-job-summary:
    description: Add the job summary to the output
    required: false
    default: 'always'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
      with:
        java-version: 11
        distribution: temurin
    - name: setup-gradle
      uses: gradle/actions/setup-gradle@748248ddd2a24f49513d8f472f81c3a07d4d50e1 # v4
      with:
          cache-overwrite-existing: true
          add-job-summary: ${{ inputs.add-job-summary }}
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@7b6a61a73bbb9793cb80ad69b8dd8ac19261834c # v3
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
      with:
        limit-access-to-actor: true
        detached: ${{ github.event.inputs.debug_detached }}