name: Shared Build Setup
description: Setup the build environment for the shared build commands
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
      with:
        java-version: 11
        distribution: temurin
        cache: gradle
    - name: setup-gradle
      uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 # v4
    - name: gradle-wrapper-validation
      uses: gradle/actions/wrapper-validation@06832c7b30a0129d7fb559bcc6e43d26f6374244 # v4
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@7b6a61a73bbb9793cb80ad69b8dd8ac19261834c # v3
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
      with:
        limit-access-to-actor: true
        detached: ${{ github.event.inputs.debug_detached }}