# j'bang - Having fun with Java scripting
:toc:
:toc-placement:

image:https://img.shields.io/github/release/maxandersen/jbang.svg[Release,link=https://github.com/maxandersen/jbang/releases]
image:https://github.com/maxandersen/jbang/workflows/ci-build/badge.svg[Build Status,link=https://github.com/maxandersen/jbang/actions]

Ever tried out Java 10+ support for running .java files directly in your shell but felt it was a bit too cumbersome ?

Then try `jbang` which gives you:

* Dependency declarations using `//DEPS <gav>` for automatic dependency resolution
* Dependency resolution caching
* (PLANNED) Launch with debug enabled for instant debugging from your favorite IDE
* (PLANNED) Generate gradle/maven file with dependencies for easy editing in your favorite IDE
* (PLANNED) Lookup dependencies with a short-hand name, i.e. `// DEPS log4j:1.2+,picocli` for quick getting started.

To use it simply install `jbang` and run `jbang yourscript.java`

toc::[]

## Installation

To use `jbang` just have Java 11+ available.

### Manual

Unzip the https://github.com/maxandersen/jbang/releases/latest[latest binary release], put the `jbang-<version>/bin` folder in to your `$PATH` and you are set.

### Homebrew

On OSX you can install `jbang` with https://brew.sh[Homebrew] using https://github.com/maxandersen/homebrew-tap/[maxandersen/tap].

  brew install maxandersen/tab/jbang

To upgrade to latest version:

  brew upgrade maxandersen/tab/jbang


## Declare dependencies with `//DEPS`

To specify dependencies you use gradle-style locators. Here is an example using `log4j`

[source, java]
```
//#!/usr/bin/env jbang

//DEPS log4j:log4j:1.2.17

import static java.lang.System.out;

import org.apache.log4j.Logger;
import org.apache.log4j.BasicConfigurator;

import java.util.Arrays;

class classpath_example {

	static final Logger logger = Logger.getLogger(classpath_example.class);

	public static void main(String[] args) {
		BasicConfigurator.configure();
		logger.info("Welcome to jbang");

		Arrays.asList(args).forEach(arg -> logger.warn("arg: " + arg));
		logger.info("\nHello from Java!");
	}
}
```

## FAQ

[qanda]
Why the name j'bang?::
  I was reading up on how to use the new shebang (#!) feature support in Java 10 and came up with the idea of port `kscript` to Java and needed a name.
From there came j'bang which is a "bad" spelling of how shebang is pronounced in french.

[qanda]
Why use of gradle resource locators rather than ?::
  kscript used it and its nice as it is a one-liner and easily parsable.

[qanda]
Why would I use Java to write scripts ? Java sucks for that...::
  Well, does it really ? With Java 8 streams, static imports and greatly improved standard java libraries it is very close to how kscript and grape looks like.
With the following advantages:
+
* works with plain Java without installing additional compiler/build tools
* all ide's support editing .java files very well, content assist etc.
* great debugging

And to be honest I built `jbang` just to see if I could and get my Java skills refreshed for the newer features in the language.
Use it at your own risk :)

## Thanks

`jbang` was heavily inspired by how `https://github.com/holgerbrandl/kscript[kscript]` by Holger Brand works.

