= JBANG-ALIAS

== NAME

jbang alias -- Manage aliases for scripts.

== SYNOPSIS

[source]
----
jbang alias [-hox] [--config=<config>] [--insecure] [--verbose] [--quiet] [--fresh] [COMMAND]
----

== DESCRIPTION

Manage aliases for scripts.

== OPTIONS

*-h*, *--help*::
Display this help and exit

*--config*=<config>::
Path to config file to be used instead of the default

*--insecure*::
Enable insecure trust of all SSL certificates.

*--verbose*::
jbang will be verbose on what it does.

*--quiet*::
jbang will be quiet, only print when error occurs.

*-o*, *--offline*::
Work offline. Fail-fast if dependencies are missing.

*--fresh*::
Make sure we use fresh (i.e. non-cached) resources.

*-x*, *--stacktrace*::
Print exceptions stacktraces to stderr (even when quiet).

== COMMANDS

* xref:jbang:cli:jbang-alias-add.adoc[*add*] - Add alias for script reference.
* xref:jbang:cli:jbang-alias-list.adoc[*list*] - Lists locally defined aliases or from the given catalog.
* xref:jbang:cli:jbang-alias-remove.adoc[*remove*] - Remove existing alias.

