// This is a generated documentation file based on picocli
// To change it update the picocli code or the genrator
// tag::picocli-generated-full-manpage[]
// tag::picocli-generated-man-section-header[]
:doctype: manpage
:revnumber: 0.71.1.26
:manmanual: JBang Manual
:mansource: 0.71.1.26
:man-linkstyle: pass:[blue R < >]
= jbang(1)

// end::picocli-generated-man-section-header[]

// tag::picocli-generated-man-section-name[]
== Name

jbang - jbang is a tool for building and running .java/.jsh scripts and jar packages.

// end::picocli-generated-man-section-name[]

// tag::picocli-generated-man-section-synopsis[]
== Synopsis

*jbang* [*-hV*] [*--verbose* | *--quiet*] [*-o* | [*--fresh*]] [COMMAND]

// end::picocli-generated-man-section-synopsis[]

// tag::picocli-generated-man-section-description[]
== Description

jbang init hello.java [args...]
      (to initialize a script)
or  jbang edit --open=code --live hello.java
      (to edit a script in IDE with live updates)
or  jbang hello.java [args...]
      (to run a .java file)
or  jbang gavsearch@jbangdev [args...]
      (to run a alias from a catalog)
or  jbang group-id:artifact-id:version [args...]
      (to run a .jar file found with a GAV id)


// end::picocli-generated-man-section-description[]

// tag::picocli-generated-man-section-options[]
== Options

*--fresh*::
  Make sure we use fresh (i.e. non-cached) resources.

*-h*, *--help*::
  Display help/info. Use 'jbang <command> -h' for detailed usage.

*-o*, *--offline*::
  Work offline. Fail-fast if dependencies are missing. No connections will be attempted

*--quiet*::
  jbang will be quiet, only print when error occurs.

*-V*, *--version*::
  Display version info (use `jbang --verbose version` for more details)

*--verbose*::
  jbang will be verbose on what it does.

// end::picocli-generated-man-section-options[]

// tag::picocli-generated-man-section-arguments[]
// end::picocli-generated-man-section-arguments[]

// tag::picocli-generated-man-section-commands[]
== Commands

xref:jbang-run.adoc[*run*]::
  Builds and runs provided script.

xref:jbang-build.adoc[*build*]::
  Compiles and stores script in the cache.

xref:jbang-edit.adoc[*edit*]::
  Setup a temporary project to edit script in an IDE.

xref:jbang-init.adoc[*init*]::
  Initialize a script.

xref:jbang-alias.adoc[*alias*]::
  Manage aliases for scripts.

xref:jbang-template.adoc[*template*]::
  Manage templates for scripts.

xref:jbang-catalog.adoc[*catalog*]::
  Manage Catalogs of aliases.

xref:jbang-trust.adoc[*trust*]::
  Manage which domains you trust to run scripts from.

xref:jbang-cache.adoc[*cache*]::
  Manage compiled scripts in the local cache.

xref:jbang-completion.adoc[*completion*]::
  Output auto-completion script for bash/zsh.
+
Usage: source <(jbang completion)

xref:jbang-jdk.adoc[*jdk*]::
  Manage Java Development Kits installed by jbang.

xref:jbang-version.adoc[*version*]::
  Display version info.

xref:jbang-wrapper.adoc[*wrapper*]::
  Manage jbang wrapper for a folder.

xref:jbang-info.adoc[*info*]::
  Provides info about the script for tools (and humans who are tools).

xref:jbang-app.adoc[*app*]::
  Manage scripts installed on the user's PATH as commands.

xref:jbang-export.adoc[*export*]::
  Export the result of a build.

// end::picocli-generated-man-section-commands[]

// tag::picocli-generated-man-section-exit-status[]
// end::picocli-generated-man-section-exit-status[]

// tag::picocli-generated-man-section-footer[]
// end::picocli-generated-man-section-footer[]

// end::picocli-generated-full-manpage[]
