= JBANG-TEMPLATE-ADD

== NAME

jbang template add -- Add template for script reference.

== SYNOPSIS

[source]
----
jbang template add [-hg] [-d=<description>] [--name=<name>] [--force] [-P=<property>] [-f=<file>] [--config=<config>] [--insecure] [--[no-]verbose] [--[no-]quiet] [--[no-]offline] [--[no-]fresh] [--[no-]stacktrace] <files>
----

== OPTIONS

*-h*, *--help*::
Display this help and exit

*-d*, *--description*=<description>::
A description for the template

*--name*=<name>::
A name for the template

*--force*::
Force overwriting of existing template

*-P*, *--property*=<property>::
Template property (key=description::defaultValue)

*-g*, *--global*::
Use the global (user) catalog file

*-f*, *--file*=<file>::
Path to the catalog file to use

*--config*=<config>::
Path to config file to be used instead of the default

*--insecure*::
Enable insecure trust of all SSL certificates.

*--[no-]verbose*::
jbang will be verbose on what it does.

*--[no-]quiet*::
jbang will be quiet, only print when error occurs.

*-o*, *--[no-]offline*::
Work offline. Fail-fast if dependencies are missing.

*--[no-]fresh*::
Make sure we use fresh (i.e. non-cached) resources.

*-x*, *--[no-]stacktrace*::
Print exceptions stacktraces to stderr (even when quiet).

== ARGUMENTS

*<files>*::
Paths or URLs to template files

