= JBANG-APP-INSTALL

== NAME

jbang app install -- Install a script as a command.

== SYNOPSIS

[source]
----
jbang app install [-hin] [-R=<runtime-option>] [--jfr] [-d] [--enableassertions] [--enablesystemassertions] [--javaagent<key>=<value>] [--[no-]cds] [--force] [--no-build] [--name=<name>] [-s=<sources>] [--files=<files>] [-T=<source-type>] [--jsh] [--catalog=<catalog>] [--jdk-providers=<jdk-providers>] [--jdk-distros=<jdk-distros>] [-j=<java>] [-m=<main>] [--module] [-C=<compile-option>] [--manifest<key>=<value>] [--[no-]integrations] [-D<key>=<value>] [--deps=<deps>] [--repos=<repos>] [--cp=<cp>] [--ignore-transitive-repositories] [-N=<native-option>] [--build-dir=<build-dir>] [--enable-preview] [--config=<config>] [--insecure] [--[no-]verbose] [--[no-]quiet] [--[no-]offline] [--[no-]fresh] [--[no-]stacktrace] [<scriptOrFile>] [<params>]
----

== OPTIONS

*-h*, *--help*::
Display this help and exit

*-R*, *--runtime-option*=<runtime-option>::
Options to pass to the Java runtime
+
Aliases: `--java-options`

*--jfr*=<jfr>::
Launch with Java Flight Recorder enabled.

*-d*, *--debug*=<debug>::
Launch with java debug enabled. Set host/port or provide key/value list of JPDA options (default: )

*--enableassertions*::
Enable assertions
+
Aliases: `--ea`

*--enablesystemassertions*::
Enable system assertions
+
Aliases: `--esa`

*--javaagent*=<key>=<value>::
Java agent to use
+
Default: ``

*--[no-]cds*::
If specified Class Data Sharing (CDS) will be used for building and running (requires Java 13+)

*-i*, *--interactive*::
Activate interactive mode

*--force*::
Force re-installation

*--no-build*::
Don't pre-build the code before installation

*--name*=<name>::
A name for the command

*-s*, *--sources*=<sources>::
Add additional sources.

*--files*=<files>::
Add additional files.

*-T*, *--source-type*=<source-type>::
Force input to be interpreted as the given type. Can be: java, jshell, groovy, kotlin, or markdown

*--jsh*::
Force input to be interpreted with jsh/jshell. Deprecated: use '--source-type jshell'

*--catalog*=<catalog>::
Path to catalog file to be used instead of the default

*--jdk-providers*=<jdk-providers>::
Use the given providers to manage JDKs

*--jdk-distros*=<jdk-distros>::
Use the given distributions to install new JDKs

*-j*, *--java*=<java>::
JDK version to use for running the script.

*-m*, *--main*=<main>::
Main class to use when running. Used primarily for running jar's. Can be a glob pattern using ? and *.

*--module*=<module>::
Treat resource as a module. Optionally with the given module name

*-C*, *--compile-option*=<compile-option>::
Options to pass to the compiler

*--manifest*=<key>=<value>::
Add entry to the JAR manifest (e.g. --manifest=Main-Class=com.example.Main)

*--[no-]integrations*::
Enable or disable integration execution (default: true)

*-D*=<key>=<value>::
set a system property
+
Default: `true`

*--deps*=<deps>::
Add additional dependencies (Use commas to separate them).

*--repos*=<repos>::
Add additional repositories.

*--cp*=<cp>::
Add class path entries.
+
Aliases: `--class-path`

*--ignore-transitive-repositories*::
Ignore remote repositories found in transitive dependencies
+
Aliases: `--itr`

*-n*, *--native*::
Build using native-image

*-N*, *--native-option*=<native-option>::
Options to pass to the native image tool

*--build-dir*=<build-dir>::
Use given directory for build results

*--enable-preview*::
Activate Java preview features

*--config*=<config>::
Path to config file to be used instead of the default

*--insecure*::
Enable insecure trust of all SSL certificates.

*--[no-]verbose*::
jbang will be verbose on what it does.

*--[no-]quiet*::
jbang will be quiet, only print when error occurs.

*-o*, *--[no-]offline*::
Work offline. Fail-fast if dependencies are missing.

*--[no-]fresh*::
Make sure we use fresh (i.e. non-cached) resources.

*-x*, *--[no-]stacktrace*::
Print exceptions stacktraces to stderr (even when quiet).

== ARGUMENTS

*<scriptOrFile>*::
A file or URL to a Java code file

*<params>*::
Parameters to pass on to the script

