= JBANG-CONFIG-SET

== NAME

jbang config set -- Set a configuration value

== SYNOPSIS

[source]
----
jbang config set [-hgox] [-f=<file>] [--config=<config>] [--insecure] [--verbose] [--quiet] [--fresh] <key> [<value>]
----

== DESCRIPTION

Set a configuration value

== OPTIONS

*-h*, *--help*::
Display this help and exit

*-g*, *--global*::
Use the global (user) config file

*-f*, *--file*=<file>::
Path to the config file to use

*--config*=<config>::
Path to config file to be used instead of the default

*--insecure*::
Enable insecure trust of all SSL certificates.

*--verbose*::
jbang will be verbose on what it does.

*--quiet*::
jbang will be quiet, only print when error occurs.

*-o*, *--offline*::
Work offline. Fail-fast if dependencies are missing.

*--fresh*::
Make sure we use fresh (i.e. non-cached) resources.

*-x*, *--stacktrace*::
Print exceptions stacktraces to stderr (even when quiet).

== ARGUMENTS

*<key>*::
The name of the configuration option to set

*<value>*::
The value to set for the configuration option

