= JBANG-CATALOG-LIST

== NAME

jbang catalog list -- Show currently defined catalogs.

== SYNOPSIS

[source]
----
jbang catalog list [-hgox] [--show-origin] [--format=<format>] [-f=<file>] [--config=<config>] [--insecure] [--verbose] [--quiet] [--fresh] [<name>]
----

== DESCRIPTION

Show currently defined catalogs.

== OPTIONS

*-h*, *--help*::
Display this help and exit

*--show-origin*::
Show the origin of the catalog

*--format*=<format>::
Specify output format ('text' or 'json')

*-g*, *--global*::
Use the global (user) catalog file

*-f*, *--file*=<file>::
Path to the catalog file to use

*--config*=<config>::
Path to config file to be used instead of the default

*--insecure*::
Enable insecure trust of all SSL certificates.

*--verbose*::
jbang will be verbose on what it does.

*--quiet*::
jbang will be quiet, only print when error occurs.

*-o*, *--offline*::
Work offline. Fail-fast if dependencies are missing.

*--fresh*::
Make sure we use fresh (i.e. non-cached) resources.

*-x*, *--stacktrace*::
Print exceptions stacktraces to stderr (even when quiet).

== ARGUMENTS

*<name>*::
The name of a catalog

