= JBANG-CATALOG

== NAME

jbang catalog -- Manage Catalogs of aliases.

== SYNOPSIS

[source]
----
jbang catalog [-h] [--config=<config>] [--insecure] [--[no-]verbose] [--[no-]quiet] [--[no-]offline] [--[no-]fresh] [--[no-]stacktrace] [COMMAND]
----

== OPTIONS

*-h*, *--help*::
Display this help and exit

*--config*=<config>::
Path to config file to be used instead of the default

*--insecure*::
Enable insecure trust of all SSL certificates.

*--[no-]verbose*::
jbang will be verbose on what it does.

*--[no-]quiet*::
jbang will be quiet, only print when error occurs.

*-o*, *--[no-]offline*::
Work offline. Fail-fast if dependencies are missing.

*--[no-]fresh*::
Make sure we use fresh (i.e. non-cached) resources.

*-x*, *--[no-]stacktrace*::
Print exceptions stacktraces to stderr (even when quiet).

== COMMANDS

* xref:jbang:cli:jbang-catalog-add.adoc[*add*] - Add a catalog.
* xref:jbang:cli:jbang-catalog-update.adoc[*update*] - Retrieve the latest contents of the catalogs.
* xref:jbang:cli:jbang-catalog-list.adoc[*list*] - Show currently defined catalogs.
* xref:jbang:cli:jbang-catalog-remove.adoc[*remove*] - Remove existing catalog.

