= JBANG-INFO

== NAME

jbang info -- Provides info about the script for tools (and humans who are tools).

== SYNOPSIS

[source]
----
jbang info [-hox] [--config=<config>] [--insecure] [--verbose] [--quiet] [--fresh] [COMMAND]
----

== DESCRIPTION

Provides info about the script for tools (and humans who are tools).

== OPTIONS

*-h*, *--help*::
Display this help and exit

*--config*=<config>::
Path to config file to be used instead of the default

*--insecure*::
Enable insecure trust of all SSL certificates.

*--verbose*::
jbang will be verbose on what it does.

*--quiet*::
jbang will be quiet, only print when error occurs.

*-o*, *--offline*::
Work offline. Fail-fast if dependencies are missing.

*--fresh*::
Make sure we use fresh (i.e. non-cached) resources.

*-x*, *--stacktrace*::
Print exceptions stacktraces to stderr (even when quiet).

== COMMANDS

* xref:jbang:cli:jbang-info-tools.adoc[*tools*] - Prints a json description usable for tools/IDE's to get classpath and more info for a jbang script/application.
* xref:jbang:cli:jbang-info-classpath.adoc[*classpath*] - Prints class-path used for this application using operating system specific path separation.
* xref:jbang:cli:jbang-info-jar.adoc[*jar*] - Prints the path to this application's JAR file.
* xref:jbang:cli:jbang-info-docs.adoc[*docs*] - Open the documentation file in the default browser.

