= JBANG-JDK-LIST

== NAME

jbang jdk list -- Lists installed JDKs.

== SYNOPSIS

[source]
----
jbang jdk list [-hadox] [--format=<format>] [--config=<config>] [--insecure] [--verbose] [--quiet] [--fresh]
----

== DESCRIPTION

Lists installed JDKs.

== OPTIONS

*-h*, *--help*::
Display this help and exit

*-a*, *--available*::
Shows versions available for installation

*-d*, *--show-details*::
Shows detailed information for each JDK (only when format=text)
+
Aliases: `--details`

*--format*=<format>::
Specify output format ('text' or 'json')

*--config*=<config>::
Path to config file to be used instead of the default

*--insecure*::
Enable insecure trust of all SSL certificates.

*--verbose*::
jbang will be verbose on what it does.

*--quiet*::
jbang will be quiet, only print when error occurs.

*-o*, *--offline*::
Work offline. Fail-fast if dependencies are missing.

*--fresh*::
Make sure we use fresh (i.e. non-cached) resources.

*-x*, *--stacktrace*::
Print exceptions stacktraces to stderr (even when quiet).

