= JBANG-CONFIG-LIST

== NAME

jbang config list -- List active configuration values

== SYNOPSIS

[source]
----
jbang config list [-hgox] [--show-origin] [--show-available] [--format=<format>] [-f=<file>] [--config=<config>] [--insecure] [--verbose] [--quiet] [--fresh]
----

== DESCRIPTION

List active configuration values

== OPTIONS

*-h*, *--help*::
Display this help and exit

*--show-origin*::
Show the origin of the configuration

*--show-available*::
Show the available key names

*--format*=<format>::
Specify output format ('text' or 'json')

*-g*, *--global*::
Use the global (user) config file

*-f*, *--file*=<file>::
Path to the config file to use

*--config*=<config>::
Path to config file to be used instead of the default

*--insecure*::
Enable insecure trust of all SSL certificates.

*--verbose*::
jbang will be verbose on what it does.

*--quiet*::
jbang will be quiet, only print when error occurs.

*-o*, *--offline*::
Work offline. Fail-fast if dependencies are missing.

*--fresh*::
Make sure we use fresh (i.e. non-cached) resources.

*-x*, *--stacktrace*::
Print exceptions stacktraces to stderr (even when quiet).

