= JBANG-CATALOG-ADD

== NAME

jbang catalog add -- Add a catalog.

== SYNOPSIS

[source]
----
jbang catalog add [-hg] [-d=<description>] [--name=<name>] [--force] [--import] [-f=<file>] [--config=<config>] [--insecure] [--[no-]verbose] [--[no-]quiet] [--[no-]offline] [--[no-]fresh] [--[no-]stacktrace] <fileOrURL>
----

== OPTIONS

*-h*, *--help*::
Display this help and exit

*-d*, *--description*=<description>::
A description for the catalog

*--name*=<name>::
A name for the catalog

*--force*::
Force overwriting of existing catalog

*--import*::
Import catalog items into the catalog's scope

*-g*, *--global*::
Use the global (user) catalog file

*-f*, *--file*=<file>::
Path to the catalog file to use

*--config*=<config>::
Path to config file to be used instead of the default

*--insecure*::
Enable insecure trust of all SSL certificates.

*--[no-]verbose*::
jbang will be verbose on what it does.

*--[no-]quiet*::
jbang will be quiet, only print when error occurs.

*-o*, *--[no-]offline*::
Work offline. Fail-fast if dependencies are missing.

*--[no-]fresh*::
Make sure we use fresh (i.e. non-cached) resources.

*-x*, *--[no-]stacktrace*::
Print exceptions stacktraces to stderr (even when quiet).

== ARGUMENTS

*<fileOrURL>*::
A file or URL to a catalog file

