= JBANG-TEMPLATE-ADD

== NAME

jbang template add -- Add template for script reference.

== SYNOPSIS

[source]
----
jbang template add [-hgox] [-d=<description>] [--name=<name>] [--force] [-P=<property>] [-f=<file>] [--config=<config>] [--insecure] [--verbose] [--quiet] [--fresh] <files>
----

== DESCRIPTION

Add template for script reference.

== OPTIONS

*-h*, *--help*::
Display this help and exit

*-d*, *--description*=<description>::
A description for the template

*--name*=<name>::
A name for the template

*--force*::
Force overwriting of existing template

*-P*, *--property*=<property>::
Template property (key=description::defaultValue)

*-g*, *--global*::
Use the global (user) catalog file

*-f*, *--file*=<file>::
Path to the catalog file to use

*--config*=<config>::
Path to config file to be used instead of the default

*--insecure*::
Enable insecure trust of all SSL certificates.

*--verbose*::
jbang will be verbose on what it does.

*--quiet*::
jbang will be quiet, only print when error occurs.

*-o*, *--offline*::
Work offline. Fail-fast if dependencies are missing.

*--fresh*::
Make sure we use fresh (i.e. non-cached) resources.

*-x*, *--stacktrace*::
Print exceptions stacktraces to stderr (even when quiet).

== ARGUMENTS

*<files>*::
Paths or URLs to template files

