= JBANG-JDK-DEFAULT

== NAME

jbang jdk default -- Sets the default JDK to be used by JBang.

== SYNOPSIS

[source]
----
jbang jdk default [-hvdox] [--format=<format>] [--config=<config>] [--insecure] [--verbose] [--quiet] [--fresh] [<versionOrId>]
----

== DESCRIPTION

Sets the default JDK to be used by JBang.

== OPTIONS

*-h*, *--help*::
Display this help and exit

*-v*, *--for-version*::
Sets the default for the specified major version

*-d*, *--show-details*::
Shows detailed information for each JDK (only when format=text)
+
Aliases: `--details`

*--format*=<format>::
Specify output format ('text' or 'json')

*--config*=<config>::
Path to config file to be used instead of the default

*--insecure*::
Enable insecure trust of all SSL certificates.

*--verbose*::
jbang will be verbose on what it does.

*--quiet*::
jbang will be quiet, only print when error occurs.

*-o*, *--offline*::
Work offline. Fail-fast if dependencies are missing.

*--fresh*::
Make sure we use fresh (i.e. non-cached) resources.

*-x*, *--stacktrace*::
Print exceptions stacktraces to stderr (even when quiet).

== ARGUMENTS

*<versionOrId>*::
The version of the JDK to select

