= JBANG-TRUST

== NAME

jbang trust -- Manage which domains you trust to run scripts from.

== SYNOPSIS

[source]
----
jbang trust [-hox] [--config=<config>] [--insecure] [--verbose] [--quiet] [--fresh] [COMMAND]
----

== DESCRIPTION

Manage which domains you trust to run scripts from.

== OPTIONS

*-h*, *--help*::
Display this help and exit

*--config*=<config>::
Path to config file to be used instead of the default

*--insecure*::
Enable insecure trust of all SSL certificates.

*--verbose*::
jbang will be verbose on what it does.

*--quiet*::
jbang will be quiet, only print when error occurs.

*-o*, *--offline*::
Work offline. Fail-fast if dependencies are missing.

*--fresh*::
Make sure we use fresh (i.e. non-cached) resources.

*-x*, *--stacktrace*::
Print exceptions stacktraces to stderr (even when quiet).

== COMMANDS

* xref:jbang:cli:jbang-trust-add.adoc[*add*] - Add trust domains.
* xref:jbang:cli:jbang-trust-list.adoc[*list*] - Show defined trust domains.
* xref:jbang:cli:jbang-trust-remove.adoc[*remove*] - Remove trust domains.

