= JBANG-APP

== NAME

jbang app -- Manage scripts installed on the user's PATH as commands.

== SYNOPSIS

[source]
----
jbang app [-hox] [--config=<config>] [--insecure] [--verbose] [--quiet] [--fresh] [COMMAND]
----

== DESCRIPTION

Manage scripts installed on the user's PATH as commands.

== OPTIONS

*-h*, *--help*::
Display this help and exit

*--config*=<config>::
Path to config file to be used instead of the default

*--insecure*::
Enable insecure trust of all SSL certificates.

*--verbose*::
jbang will be verbose on what it does.

*--quiet*::
jbang will be quiet, only print when error occurs.

*-o*, *--offline*::
Work offline. Fail-fast if dependencies are missing.

*--fresh*::
Make sure we use fresh (i.e. non-cached) resources.

*-x*, *--stacktrace*::
Print exceptions stacktraces to stderr (even when quiet).

== COMMANDS

* xref:jbang:cli:jbang-app-install.adoc[*install*] - Install a script as a command.
* xref:jbang:cli:jbang-app-list.adoc[*list*] - Lists installed commands.
* xref:jbang:cli:jbang-app-uninstall.adoc[*uninstall*] - Removes a previously installed command.
* xref:jbang:cli:jbang-app-setup.adoc[*setup*] - Make jbang commands available for the user.

