= JBANG-JDK-DEFAULT

== NAME

jbang jdk default -- Sets the default JDK to be used by JBang.

== SYNOPSIS

[source]
----
jbang jdk default [-hvd] [--format=<format>] [--config=<config>] [--insecure] [--[no-]verbose] [--[no-]quiet] [--[no-]offline] [--[no-]fresh] [--[no-]stacktrace] [<versionOrId>]
----

== OPTIONS

*-h*, *--help*::
Display this help and exit

*-v*, *--for-version*::
Sets the default for the specified major version

*-d*, *--show-details*::
Shows detailed information for each JDK (only when format=text)
+
Aliases: `--details`

*--format*=<format>::
Specify output format ('text' or 'json')

*--config*=<config>::
Path to config file to be used instead of the default

*--insecure*::
Enable insecure trust of all SSL certificates.

*--[no-]verbose*::
jbang will be verbose on what it does.

*--[no-]quiet*::
jbang will be quiet, only print when error occurs.

*-o*, *--[no-]offline*::
Work offline. Fail-fast if dependencies are missing.

*--[no-]fresh*::
Make sure we use fresh (i.e. non-cached) resources.

*-x*, *--[no-]stacktrace*::
Print exceptions stacktraces to stderr (even when quiet).

== ARGUMENTS

*<versionOrId>*::
The version of the JDK to select

