= JBANG-EXPORT-GRADLE

== NAME

jbang export gradle -- Exports a Gradle project

== SYNOPSIS

[source]
----
jbang export gradle [-hnox] [-g=<group>] [-a=<artifact>] [-v=<version>] [-O=<output>] [--force] [-s=<sources>] [--files=<files>] [-T=<source-type>] [--jsh] [--catalog=<catalog>] [-j=<java>] [-m=<main>] [--module] [-C=<compile-option>] [--manifest<key>=<value>] [--[no-]integrations] [-D<key>=<value>] [--deps=<deps>] [--repos=<repos>] [--cp=<cp>] [--ignore-transitive-repositories] [-N=<native-option>] [--build-dir=<build-dir>] [--enable-preview] [--config=<config>] [--insecure] [--verbose] [--quiet] [--fresh] [<scriptOrFile>]
----

== DESCRIPTION

Exports a Gradle project

== OPTIONS

*-h*, *--help*::
Display this help and exit

*-g*, *--group*=<group>::
The group ID to use for the exported project.

*-a*, *--artifact*=<artifact>::
The artifact ID to use for the exported project.

*-v*, *--version*=<version>::
The version to use for the exported project.

*-O*, *--output*=<output>::
The name or path to use for the exported file.

*--force*::
Force export, i.e. overwrite exported file if already exists

*-s*, *--sources*=<sources>::
Add additional sources.

*--files*=<files>::
Add additional files.

*-T*, *--source-type*=<source-type>::
Force input to be interpreted as the given type. Can be: java, jshell, groovy, kotlin, or markdown

*--jsh*::
Force input to be interpreted with jsh/jshell. Deprecated: use '--source-type jshell'

*--catalog*=<catalog>::
Path to catalog file to be used instead of the default

*-j*, *--java*=<java>::
JDK version to use for running the script.

*-m*, *--main*=<main>::
Main class to use when running. Used primarily for running jar's. Can be a glob pattern using ? and *.

*--module*=<module>::
Treat resource as a module. Optionally with the given module name

*-C*, *--compile-option*=<compile-option>::
Options to pass to the compiler

*--manifest*=<key>=<value>::

*--[no-]integrations*::
Enable or disable integration execution (default: true)

*-D*=<key>=<value>::
set a system property
+
Default: `true`

*--deps*=<deps>::
Add additional dependencies (Use commas to separate them).

*--repos*=<repos>::
Add additional repositories.

*--cp*=<cp>::
Add class path entries.
+
Aliases: `--class-path`

*--ignore-transitive-repositories*::
Ignore remote repositories found in transitive dependencies
+
Aliases: `--itr`

*-n*, *--native*::
Build using native-image

*-N*, *--native-option*=<native-option>::
Options to pass to the native image tool

*--build-dir*=<build-dir>::
Use given directory for build results

*--enable-preview*::
Activate Java preview features

*--config*=<config>::
Path to config file to be used instead of the default

*--insecure*::
Enable insecure trust of all SSL certificates.

*--verbose*::
jbang will be verbose on what it does.

*--quiet*::
jbang will be quiet, only print when error occurs.

*-o*, *--offline*::
Work offline. Fail-fast if dependencies are missing.

*--fresh*::
Make sure we use fresh (i.e. non-cached) resources.

*-x*, *--stacktrace*::
Print exceptions stacktraces to stderr (even when quiet).

== ARGUMENTS

*<scriptOrFile>*::
A file or URL to a Java code file

