= JBANG-EDIT

== NAME

jbang edit -- Setup a temporary project to edit script in an IDE.

== SYNOPSIS

[source]
----
jbang edit [-hbox] [-s=<sources>] [--files=<files>] [-T=<source-type>] [--jsh] [--catalog=<catalog>] [-D<key>=<value>] [--deps=<deps>] [--repos=<repos>] [--cp=<cp>] [--ignore-transitive-repositories] [--live] [--open] [--no-open] [--config=<config>] [--insecure] [--verbose] [--quiet] [--fresh] [<scriptOrFile>] [<additionalFiles>]
----

== DESCRIPTION

Setup a temporary project to edit script in an IDE.

== OPTIONS

*-h*, *--help*::
Display this help and exit

*-s*, *--sources*=<sources>::
Add additional sources.

*--files*=<files>::
Add additional files.

*-T*, *--source-type*=<source-type>::
Force input to be interpreted as the given type. Can be: java, jshell, groovy, kotlin, or markdown

*--jsh*::
Force input to be interpreted with jsh/jshell. Deprecated: use '--source-type jshell'

*--catalog*=<catalog>::
Path to catalog file to be used instead of the default

*-D*=<key>=<value>::
set a system property
+
Default: `true`

*--deps*=<deps>::
Add additional dependencies (Use commas to separate them).

*--repos*=<repos>::
Add additional repositories.

*--cp*=<cp>::
Add class path entries.
+
Aliases: `--class-path`

*--ignore-transitive-repositories*::
Ignore remote repositories found in transitive dependencies
+
Aliases: `--itr`

*--live*::
Open directory in IDE's that support JBang or generate temporary project with option to regenerate project on dependency changes.

*--open*=<open>::
Opens editor/IDE on the temporary project.

*--no-open*::
Explicitly prevent JBang from opening an editor/IDE

*-b*, *--sandbox*::
Edit in sandbox mode. Useful when the editor/IDE used has no JBang support

*--config*=<config>::
Path to config file to be used instead of the default

*--insecure*::
Enable insecure trust of all SSL certificates.

*--verbose*::
jbang will be verbose on what it does.

*--quiet*::
jbang will be quiet, only print when error occurs.

*-o*, *--offline*::
Work offline. Fail-fast if dependencies are missing.

*--fresh*::
Make sure we use fresh (i.e. non-cached) resources.

*-x*, *--stacktrace*::
Print exceptions stacktraces to stderr (even when quiet).

== ARGUMENTS

*<scriptOrFile>*::
A file or URL to a Java code file

*<additionalFiles>*::
Additional files

