= JBANG-CACHE-CLEAR

== NAME

jbang cache clear -- Clear the various caches used by jbang. By default this will clear the JAR, script, stdin and URL caches.

== SYNOPSIS

[source]
----
jbang cache clear [-hox] [--[no-]url] [--[no-]jar] [--[no-]deps] [--[no-]jdk] [--[no-]kotlinc] [--[no-]groovyc] [--[no-]project] [--[no-]script] [--[no-]stdin] [--all] [--config=<config>] [--insecure] [--verbose] [--quiet] [--fresh]
----

== DESCRIPTION

Clear the various caches used by jbang. By default this will clear the JAR, script, stdin and URL caches.

== OPTIONS

*-h*, *--help*::
Display this help and exit

*--[no-]url*::
clear URL cache only

*--[no-]jar*::
clear JAR cache only

*--[no-]deps*::
clear dependency cache only

*--[no-]jdk*::
clear JDK cache only

*--[no-]kotlinc*::
clear kotlinc cache only

*--[no-]groovyc*::
clear groovyc cache only

*--[no-]project*::
clear temporary projects cache only

*--[no-]script*::
clear script cache only

*--[no-]stdin*::
clear stdin cache only

*--all*::
clear all caches

*--config*=<config>::
Path to config file to be used instead of the default

*--insecure*::
Enable insecure trust of all SSL certificates.

*--verbose*::
jbang will be verbose on what it does.

*--quiet*::
jbang will be quiet, only print when error occurs.

*-o*, *--offline*::
Work offline. Fail-fast if dependencies are missing.

*--fresh*::
Make sure we use fresh (i.e. non-cached) resources.

*-x*, *--stacktrace*::
Print exceptions stacktraces to stderr (even when quiet).

