= JBANG-APP

== NAME

jbang app -- Manage scripts installed on the user's PATH as commands.

== SYNOPSIS

[source]
----
jbang app [-h] [--config=<config>] [--insecure] [--[no-]verbose] [--[no-]quiet] [--[no-]offline] [--[no-]fresh] [--[no-]stacktrace] [COMMAND]
----

== OPTIONS

*-h*, *--help*::
Display this help and exit

*--config*=<config>::
Path to config file to be used instead of the default

*--insecure*::
Enable insecure trust of all SSL certificates.

*--[no-]verbose*::
jbang will be verbose on what it does.

*--[no-]quiet*::
jbang will be quiet, only print when error occurs.

*-o*, *--[no-]offline*::
Work offline. Fail-fast if dependencies are missing.

*--[no-]fresh*::
Make sure we use fresh (i.e. non-cached) resources.

*-x*, *--[no-]stacktrace*::
Print exceptions stacktraces to stderr (even when quiet).

== COMMANDS

* xref:jbang:cli:jbang-app-install.adoc[*install*] - Install a script as a command.
* xref:jbang:cli:jbang-app-list.adoc[*list*] - Lists installed commands.
* xref:jbang:cli:jbang-app-uninstall.adoc[*uninstall*] - Removes a previously installed command.
* xref:jbang:cli:jbang-app-setup.adoc[*setup*] - Make jbang commands available for the user.

