= JBANG-INIT

== NAME

jbang init -- Initialize a script.

== SYNOPSIS

[source]
----
jbang init [-h] [-j=<java>] [--ai-provider=<ai-provider>] [--ai-api-key=<ai-api-key>] [--ai-endpoint=<ai-endpoint>] [--ai-model=<ai-model>] [-t=<template>] [--force] [--edit] [-D<key>=<value>] [--deps=<deps>] [--config=<config>] [--insecure] [--[no-]verbose] [--[no-]quiet] [--[no-]offline] [--[no-]fresh] [--[no-]stacktrace] <scriptOrFile> [<params>]
----

== OPTIONS

*-h*, *--help*::
Display this help and exit

*-j*, *--java*=<java>::
JDK version to use for running the script.

*--ai-provider*=<ai-provider>::
Provider to use (openai, openrouter, etc.) when using init with a prompt
+
Default: `${env:JBANG_AI_PROVIDER:-}`

*--ai-api-key*=<ai-api-key>::
API Key/token to use for the AI Provider
+
Default: `${env:JBANG_AI_API_KEY:-}`

*--ai-endpoint*=<ai-endpoint>::
OpenAI compatible Endpoint to use for the AI Provider when using init with a prompt
+
Default: `${env:JBANG_AI_ENDPOINT:-}`

*--ai-model*=<ai-model>::
Model string to use for init prompting
+
Default: `${env:JBANG_AI_MODEL:-}`

*-t*, *--template*=<template>::
Init script with a java class useful for scripting

*--force*::
Force overwrite of existing files

*--edit*::
Open editor on the generated file(s)

*-D*=<key>=<value>::
set a system property

*--deps*=<deps>::
Add additional dependencies (Use commas to separate them).

*--config*=<config>::
Path to config file to be used instead of the default

*--insecure*::
Enable insecure trust of all SSL certificates.

*--[no-]verbose*::
jbang will be verbose on what it does.

*--[no-]quiet*::
jbang will be quiet, only print when error occurs.

*-o*, *--[no-]offline*::
Work offline. Fail-fast if dependencies are missing.

*--[no-]fresh*::
Make sure we use fresh (i.e. non-cached) resources.

*-x*, *--[no-]stacktrace*::
Print exceptions stacktraces to stderr (even when quiet).

== ARGUMENTS

*<scriptOrFile>*::
A file or URL to a Java code file

*<params>*::
Parameters to pass on to the generation

