= JBANG-ALIAS-LIST

== NAME

jbang alias list -- Lists locally defined aliases or from the given catalog.

== SYNOPSIS

[source]
----
jbang alias list [-hgox] [-f=<file>] [--show-origin] [--format=<format>] [--config=<config>] [--insecure] [--verbose] [--quiet] [--fresh] [<catalogName>]
----

== DESCRIPTION

Lists locally defined aliases or from the given catalog.

== OPTIONS

*-h*, *--help*::
Display this help and exit

*-g*, *--global*::
Use the global (user) catalog file

*-f*, *--file*=<file>::
Path to the catalog file to use

*--show-origin*::
Show the origin of the alias

*--format*=<format>::
Specify output format ('text' or 'json')

*--config*=<config>::
Path to config file to be used instead of the default

*--insecure*::
Enable insecure trust of all SSL certificates.

*--verbose*::
jbang will be verbose on what it does.

*--quiet*::
jbang will be quiet, only print when error occurs.

*-o*, *--offline*::
Work offline. Fail-fast if dependencies are missing.

*--fresh*::
Make sure we use fresh (i.e. non-cached) resources.

*-x*, *--stacktrace*::
Print exceptions stacktraces to stderr (even when quiet).

== ARGUMENTS

*<catalogName>*::
The name of a catalog

