= JBANG-CONFIG

== NAME

jbang config -- Read and write configuration options.

== SYNOPSIS

[source]
----
jbang config [-hox] [--config=<config>] [--insecure] [--verbose] [--quiet] [--fresh] [COMMAND]
----

== DESCRIPTION

Read and write configuration options.

== OPTIONS

*-h*, *--help*::
Display this help and exit

*--config*=<config>::
Path to config file to be used instead of the default

*--insecure*::
Enable insecure trust of all SSL certificates.

*--verbose*::
jbang will be verbose on what it does.

*--quiet*::
jbang will be quiet, only print when error occurs.

*-o*, *--offline*::
Work offline. Fail-fast if dependencies are missing.

*--fresh*::
Make sure we use fresh (i.e. non-cached) resources.

*-x*, *--stacktrace*::
Print exceptions stacktraces to stderr (even when quiet).

== COMMANDS

* xref:jbang:cli:jbang-config-get.adoc[*get*] - Get a configuration value
* xref:jbang:cli:jbang-config-set.adoc[*set*] - Set a configuration value
* xref:jbang:cli:jbang-config-unset.adoc[*unset*] - Remove a configuration value
* xref:jbang:cli:jbang-config-list.adoc[*list*] - List active configuration values

