= JBANG-CONFIG-LIST

== NAME

jbang config list -- List active configuration values

== SYNOPSIS

[source]
----
jbang config list [-hg] [--show-origin] [--show-available] [--format=<format>] [-f=<file>] [--config=<config>] [--insecure] [--[no-]verbose] [--[no-]quiet] [--[no-]offline] [--[no-]fresh] [--[no-]stacktrace]
----

== OPTIONS

*-h*, *--help*::
Display this help and exit

*--show-origin*::
Show the origin of the configuration

*--show-available*::
Show the available key names

*--format*=<format>::
Specify output format ('text' or 'json')

*-g*, *--global*::
Use the global (user) config file

*-f*, *--file*=<file>::
Path to the config file to use

*--config*=<config>::
Path to config file to be used instead of the default

*--insecure*::
Enable insecure trust of all SSL certificates.

*--[no-]verbose*::
jbang will be verbose on what it does.

*--[no-]quiet*::
jbang will be quiet, only print when error occurs.

*-o*, *--[no-]offline*::
Work offline. Fail-fast if dependencies are missing.

*--[no-]fresh*::
Make sure we use fresh (i.e. non-cached) resources.

*-x*, *--[no-]stacktrace*::
Print exceptions stacktraces to stderr (even when quiet).

