= JBANG-TEMPLATE

== NAME

jbang template -- Manage templates for scripts.

== SYNOPSIS

[source]
----
jbang template [-hox] [--config=<config>] [--insecure] [--verbose] [--quiet] [--fresh] [COMMAND]
----

== DESCRIPTION

Manage templates for scripts.

== OPTIONS

*-h*, *--help*::
Display this help and exit

*--config*=<config>::
Path to config file to be used instead of the default

*--insecure*::
Enable insecure trust of all SSL certificates.

*--verbose*::
jbang will be verbose on what it does.

*--quiet*::
jbang will be quiet, only print when error occurs.

*-o*, *--offline*::
Work offline. Fail-fast if dependencies are missing.

*--fresh*::
Make sure we use fresh (i.e. non-cached) resources.

*-x*, *--stacktrace*::
Print exceptions stacktraces to stderr (even when quiet).

== COMMANDS

* xref:jbang:cli:jbang-template-add.adoc[*add*] - Add template for script reference.
* xref:jbang:cli:jbang-template-list.adoc[*list*] - Lists locally defined templates or from the given catalog.
* xref:jbang:cli:jbang-template-remove.adoc[*remove*] - Remove existing template.

