= JBANG-CATALOG

== NAME

jbang catalog -- Manage Catalogs of aliases.

== SYNOPSIS

[source]
----
jbang catalog [-hox] [--config=<config>] [--insecure] [--verbose] [--quiet] [--fresh] [COMMAND]
----

== DESCRIPTION

Manage Catalogs of aliases.

== OPTIONS

*-h*, *--help*::
Display this help and exit

*--config*=<config>::
Path to config file to be used instead of the default

*--insecure*::
Enable insecure trust of all SSL certificates.

*--verbose*::
jbang will be verbose on what it does.

*--quiet*::
jbang will be quiet, only print when error occurs.

*-o*, *--offline*::
Work offline. Fail-fast if dependencies are missing.

*--fresh*::
Make sure we use fresh (i.e. non-cached) resources.

*-x*, *--stacktrace*::
Print exceptions stacktraces to stderr (even when quiet).

== COMMANDS

* xref:jbang:cli:jbang-catalog-add.adoc[*add*] - Add a catalog.
* xref:jbang:cli:jbang-catalog-update.adoc[*update*] - Retrieve the latest contents of the catalogs.
* xref:jbang:cli:jbang-catalog-list.adoc[*list*] - Show currently defined catalogs.
* xref:jbang:cli:jbang-catalog-remove.adoc[*remove*] - Remove existing catalog.

