= JBANG-JDK-INSTALL

== NAME

jbang jdk install -- Installs a JDK.

== SYNOPSIS

[source]
----
jbang jdk install [-hf] [--jdk-providers=<jdk-providers>] [--jdk-distros=<jdk-distros>] [--config=<config>] [--insecure] [--[no-]verbose] [--[no-]quiet] [--[no-]offline] [--[no-]fresh] [--[no-]stacktrace] <versionOrId> [<existingJdkPath>]
----

== OPTIONS

*-h*, *--help*::
Display this help and exit

*--jdk-providers*=<jdk-providers>::
Use the given providers to manage JDKs

*--jdk-distros*=<jdk-distros>::
Use the given distributions to install new JDKs

*-f*, *--force*::
Force installation even when already installed

*--config*=<config>::
Path to config file to be used instead of the default

*--insecure*::
Enable insecure trust of all SSL certificates.

*--[no-]verbose*::
jbang will be verbose on what it does.

*--[no-]quiet*::
jbang will be quiet, only print when error occurs.

*-o*, *--[no-]offline*::
Work offline. Fail-fast if dependencies are missing.

*--[no-]fresh*::
Make sure we use fresh (i.e. non-cached) resources.

*-x*, *--[no-]stacktrace*::
Print exceptions stacktraces to stderr (even when quiet).

== ARGUMENTS

*<versionOrId>*::
The version or id to install

*<existingJdkPath>*::
Pre installed JDK path

