= JBANG-JDK-LIST

== NAME

jbang jdk list -- Lists installed JDKs.

== SYNOPSIS

[source]
----
jbang jdk list [-haPDd] [--jdk-providers=<jdk-providers>] [--jdk-distros=<jdk-distros>] [--format=<format>] [--config=<config>] [--insecure] [--[no-]verbose] [--[no-]quiet] [--[no-]offline] [--[no-]fresh] [--[no-]stacktrace]
----

== OPTIONS

*-h*, *--help*::
Display this help and exit

*--jdk-providers*=<jdk-providers>::
Use the given providers to manage JDKs

*--jdk-distros*=<jdk-distros>::
Use the given distributions to install new JDKs

*-a*, *--available*::
Shows versions available for installation

*-P*, *--providers*::
Shows available providers

*-D*, *--distros*::
Shows distributions available for installation

*-d*, *--show-details*::
Shows detailed information for each JDK (only when format=text)
+
Aliases: `--details`

*--format*=<format>::
Specify output format ('text' or 'json')

*--config*=<config>::
Path to config file to be used instead of the default

*--insecure*::
Enable insecure trust of all SSL certificates.

*--[no-]verbose*::
jbang will be verbose on what it does.

*--[no-]quiet*::
jbang will be quiet, only print when error occurs.

*-o*, *--[no-]offline*::
Work offline. Fail-fast if dependencies are missing.

*--[no-]fresh*::
Make sure we use fresh (i.e. non-cached) resources.

*-x*, *--[no-]stacktrace*::
Print exceptions stacktraces to stderr (even when quiet).

