site.url=https://puppy.xam.dk
site.slugify-files=false
quarkus.default-locale=en

# Build-time static export configuration for GitHub Pages.
quarkus.roq.generator.output-dir=roq

%dev.site.draft=true
%dev.site.future=true
