= Native Images with JBundle
:idprefix:
:idseparator: -
ifndef::env-github[]
:icons: font
endif::[]
ifdef::env-github[]
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

https://jbundle.avelino.run/[JBundle] can be used with JBang to compile your Java scripts into standalone native executables.

== Why JBundle?

The GraalVM native-image can be challenging to use due to slow compilations, complex reflection configurations, and library incompatibilities.

JBundle offers a more practical and easy to use solution by bundling a minimal JVM runtime with your uberjar into a single executable. The result is a single executable file, without any  external dependencies, and with full JVM compatibility.

== Native Images

https://jbundle.avelino.run/[JBundle] makes it easy to create native images from JBang scripts without the need for complex configuration. JBundle uses `jlink` to analyze your application and its dependencies, then generates an native executable with a minimal embedded JVM runtime providing only the necessary modules required by your application.

* Step 0 - Create a JBang script
** jbang init hello.java
* Step 1 - create a JBang fatjar
** jbang export fatjar hello.java
* Step 2 - use JBundle to create a native image from the fatjar
**  jbundle build --input ./hello-fatjar.jar --output ./dist/hello  --no-appcds
* Step 3 - run the native image
** ./dist/hello
+
Hello World

== Limitations

JBundle is currently only supported on Linux and MacOS.