= tz.java - a quick time zone converter
:source-highlighter: highlight.js
:icons: font

`link:tz.java[]` is a small cli to quickly convert a local time (i.e. '15:00') to its corresponding time in a list of timezones.

Useful in email and chat to discuss meeting or other event time starts.

You run it by using `jbang tz.java` or if in non-Windows just run `./tz.java` with a time parameter:

[source,shell]
----
./tz.java 15:00
07:00 PT / 10:00 ET / 15:00 BT / 16:00 CET / 20:30 IT / 01:00 AET
----

By default a common set of timezones world wide are used.

If you want to specify you own timezone list you pass that in as additional parameters:

----
./tz.java 15:00 CET Europe/London IST
16:00 CET / 15:00 BT / 20:30 IT
----

Note, the output uses the "shorthand" id for TZ info so `IST` becomes `IT`

== How is it made ?

The main app is a picocli command line implementation.

At start we have the parameters:

[source,java]
----
include::tz.java[tags=parameters,indent=0]
----
<.> Time is a timestamp and picocli will automatically convert it to a `LocalTime`.
<.> For the timezones we need a Custom converter to ensure more short hand ids will work.
<.> Default values for a list of strings are possible using `split=","`
[source,java]
----
include::tz.java[tags=zoneconverter,indent=0]
----
<.> `SHORT_IDS` here adds more mapping for common timezone shorthand ids. 

At the end the final conversion is done and printed out.

[source,java]
----
include::tz.java[tags=conversion,indent=0]
----

Enjoy!
