== How to run integration tests

In addition to the unit tests driven by gradle this directory
contains tests using https://github.com/andamira/aserta[aserta].

A bash driven testing suite runner which allows to do easy testing
running in a shell.

To run the tests first make sure you've built jbang first, added `jbang` to the path, cd to this directory and run the link:test_suite.sh[test_suite.sh].

[source, bash]
----
./gradlew build install
export PATH=`pwd`/build/install/jbang/bin:$PATH
cd itests
./test_suite.sh
----

== Experimental Karate

All the `*.feature` are written and run using https://github.com/intuit/karate[Karate].

The only prerequisite is to make sure the `jbang` you want to test is on your path.

You can run them by calling `./itests.sh` which will use Gradle to do a build and install to 
have latest version on `PATH`; or if you want to experiment
run `jbang karate.java *.feature` directly.

It is intended that eventually these Karate tests will replace the shell based tests as 
Karate can (in theory) run these on both *nix and Windows systems.
s

