package dev.jbang.docs;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Path;
import java.util.*;
import java.util.regex.*;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;

/**
 * Extracts type documentation from javadoc JAR files (HTML pages generated by
 * the javadoc tool). Parses HTML structure using regex to extract type
 * descriptions, member signatures, parameter docs, and return descriptions.
 * Matches jbx behavior.
 */
public class JavadocHtmlParser {

	private static final Pattern DETAIL_SECTION_RE = Pattern
		.compile("(?s)<section[^>]*class=\"[^\"]*detail[^\"]*\"[^>]*>(.*?)</section>");
	private static final Pattern MEMBER_SIGNATURE_RE = Pattern
		.compile("(?s)<div[^>]*class=\"[^\"]*member-signature[^\"]*\"[^>]*>(.*?)</div>");
	private static final Pattern BLOCK_RE = Pattern
		.compile("(?s)<div[^>]*class=\"[^\"]*block[^\"]*\"[^>]*>(.*?)</div>");
	private static final Pattern PARAM_DESC_RE = Pattern.compile("(?s)<dd>\\s*<code>(.*?)</code>\\s*-\\s*(.*?)</dd>");
	private static final Pattern RETURN_DESC_RE = Pattern.compile("(?s)<dt>Returns:</dt>\\s*<dd>(.*?)</dd>");
	private static final Pattern HTML_TAGS_RE = Pattern.compile("(?s)<[^>]+>");
	private static final Pattern PRE_RE = Pattern.compile("(?s)<pre[^>]*>(.*?)</pre>");

	/**
	 * Extract all types from a javadoc JAR.
	 *
	 * @param jarPath path to the javadoc JAR
	 * @return list of documented types, sorted by qualified name
	 */
	public static List<DocsType> parse(Path jarPath) throws IOException {
		List<DocsType> types = new ArrayList<>();
		try (ZipFile zip = new ZipFile(jarPath.toFile())) {
			Enumeration<? extends ZipEntry> entries = zip.entries();
			while (entries.hasMoreElements()) {
				ZipEntry entry = entries.nextElement();
				String name = entry.getName();
				if (!isJavadocTypePage(name)) {
					continue;
				}
				String html = new String(readAllBytes(zip.getInputStream(entry)));
				DocsType type = parseTypePage(name, html);
				if (type != null) {
					types.add(type);
				}
			}
		}
		types.sort(Comparator.comparing(DocsType::getQualifiedName));
		return types;
	}

	/**
	 * Determine whether a ZIP entry name represents a javadoc type page (as opposed
	 * to package-summary, index, overview, etc.).
	 */
	static boolean isJavadocTypePage(String name) {
		if (!name.endsWith(".html")) {
			return false;
		}
		if (name.contains("-")) {
			return false;
		}
		if (name.endsWith("/package-summary.html")
				|| name.endsWith("/module-summary.html")
				|| name.endsWith("/overview-summary.html")
				|| name.endsWith("/index.html")) {
			return false;
		}
		// File name must start with an uppercase letter (type pages)
		int lastSlash = name.lastIndexOf('/');
		String fileName = lastSlash >= 0 ? name.substring(lastSlash + 1) : name;
		return !fileName.isEmpty() && Character.isUpperCase(fileName.charAt(0));
	}

	/**
	 * Parse a single javadoc HTML page and return the corresponding DocsType, or
	 * null if the page cannot be parsed.
	 */
	static DocsType parseTypePage(String path, String html) {
		String qualifiedName = path.replace('/', '.').replaceAll("\\.html$", "");
		int lastDot = qualifiedName.lastIndexOf('.');
		String packageName = lastDot >= 0 ? qualifiedName.substring(0, lastDot) : "";
		String name = lastDot >= 0 ? qualifiedName.substring(lastDot + 1) : qualifiedName;

		// Determine kind from normalized text
		String text = normalizeDocText(stripHtmlTags(html));
		DocsType.Kind kind;
		if (text.contains("interface " + name)) {
			kind = DocsType.Kind.INTERFACE;
		} else if (text.contains("enum " + name)) {
			kind = DocsType.Kind.ENUM;
		} else if (text.contains("record " + name)) {
			kind = DocsType.Kind.RECORD;
		} else {
			kind = DocsType.Kind.CLASS;
		}

		String description = extractTypeDescription(html);
		List<String> examples = extractExamples(html);
		List<MemberDoc> memberDocs = extractMemberDocs(html);

		DocsType type = new DocsType();
		type.setKind(kind);
		type.setName(name);
		type.setQualifiedName(qualifiedName);
		type.setPackageName(packageName);
		type.setVisibility("public");
		type.setModifiers(Collections.singletonList("public"));
		type.setDescription(description);
		type.setExamples(examples);

		for (MemberDoc doc : memberDocs) {
			DocsMember member = JavaSourceParser.parseMemberDeclaration(
					doc.signature, packageName, name, Collections.emptyList());
			if (member == null) {
				continue;
			}
			enrichMemberWithJavadoc(member, doc);
			switch (member.getKind()) {
			case FIELD:
				type.getFields().add(member);
				break;
			case CONSTRUCTOR:
				type.getConstructors().add(member);
				break;
			case METHOD:
				type.getMethods().add(member);
				break;
			}
		}

		return type;
	}

	private static void enrichMemberWithJavadoc(DocsMember member, MemberDoc doc) {
		if (doc.description != null) {
			member.setDescription(doc.description);
		}
		if (doc.returnDescription != null) {
			member.setReturnDescription(doc.returnDescription);
		}
		if (doc.parameterDescriptions != null && !doc.parameterDescriptions.isEmpty()) {
			for (DocsType.DocsParameter param : member.getParameters()) {
				for (String[] nameDesc : doc.parameterDescriptions) {
					if (nameDesc[0].equals(param.getName())) {
						param.setDescription(nameDesc[1]);
						break;
					}
				}
			}
		}
	}

	/**
	 * Extract member detail sections from HTML and return structured docs for each.
	 */
	static List<MemberDoc> extractMemberDocs(String html) {
		List<MemberDoc> members = new ArrayList<>();
		Matcher detailMatcher = DETAIL_SECTION_RE.matcher(html);
		while (detailMatcher.find()) {
			String detail = detailMatcher.group(1);
			Matcher sigMatcher = MEMBER_SIGNATURE_RE.matcher(detail);
			if (!sigMatcher.find()) {
				continue;
			}
			String signature = normalizeDocText(stripHtmlTags(sigMatcher.group(1)));
			if (signature.isEmpty()) {
				continue;
			}
			MemberDoc doc = new MemberDoc();
			doc.signature = signature;
			doc.description = extractMemberDescription(detail);
			doc.parameterDescriptions = extractParameterDescriptions(detail);
			doc.returnDescription = extractReturnDescription(detail);
			members.add(doc);
		}
		// Fallback: use any member-signature divs if no detail sections found
		if (members.isEmpty()) {
			Matcher sigMatcher = MEMBER_SIGNATURE_RE.matcher(html);
			while (sigMatcher.find()) {
				String signature = normalizeDocText(stripHtmlTags(sigMatcher.group(1)));
				if (!signature.isEmpty()) {
					MemberDoc doc = new MemberDoc();
					doc.signature = signature;
					members.add(doc);
				}
			}
		}
		return members;
	}

	/** Extract the type-level description from HTML. */
	static String extractTypeDescription(String html) {
		String[] patterns = {
				"(?s)<section[^>]*class=\"[^\"]*(?:class|interface|enum|record)-description[^\"]*\"[^>]*>.*?<div[^>]*class=\"[^\"]*block[^\"]*\"[^>]*>(.*?)</div>",
				"(?s)<div[^>]*class=\"[^\"]*description[^\"]*\"[^>]*>.*?<div[^>]*class=\"[^\"]*block[^\"]*\"[^>]*>(.*?)</div>"
		};
		for (String pattern : patterns) {
			Matcher m = Pattern.compile(pattern).matcher(html);
			if (m.find()) {
				String text = normalizeDocText(stripHtmlTags(m.group(1)));
				if (!text.isEmpty()) {
					return text;
				}
			}
		}
		return null;
	}

	/** Extract the first block description inside a detail section. */
	static String extractMemberDescription(String detailHtml) {
		Matcher m = BLOCK_RE.matcher(detailHtml);
		if (m.find()) {
			String text = normalizeDocText(stripHtmlTags(m.group(1)));
			return text.isEmpty() ? null : text;
		}
		return null;
	}

	/** Extract parameter name/description pairs from a detail section. */
	static List<String[]> extractParameterDescriptions(String detailHtml) {
		List<String[]> result = new ArrayList<>();
		Matcher m = PARAM_DESC_RE.matcher(detailHtml);
		while (m.find()) {
			String paramName = normalizeDocText(stripHtmlTags(m.group(1)));
			String desc = normalizeDocText(stripHtmlTags(m.group(2)));
			if (!paramName.isEmpty() && !desc.isEmpty()) {
				result.add(new String[] { paramName, desc });
			}
		}
		return result;
	}

	/** Extract return description from a detail section. */
	static String extractReturnDescription(String detailHtml) {
		Matcher m = RETURN_DESC_RE.matcher(detailHtml);
		if (m.find()) {
			String text = normalizeDocText(stripHtmlTags(m.group(1)));
			return text.isEmpty() ? null : text;
		}
		return null;
	}

	/**
	 * Extract code examples from {@code 
	 * 
	 * 
	
	<pre>
	 * } blocks, excluding type/member signatures.
	 */
	static List<String> extractExamples(String html) {
		List<String> examples = new ArrayList<>();
		Matcher m = PRE_RE.matcher(html);
		while (m.find()) {
			String raw = stripHtmlTags(m.group(1)).trim();
			if (raw.isEmpty()) {
				continue;
			}
			String normalized = normalizeDocText(raw);
			if (!isJavadocMemberSignature(normalized) && !isJavadocTypeSignature(normalized)
					&& !examples.contains(raw)) {
				examples.add(raw);
			}
		}
		return examples;
	}

	/** Strip HTML tags and unescape HTML entities. */
	static String stripHtmlTags(String input) {
		String stripped = HTML_TAGS_RE.matcher(input).replaceAll(" ");
		return htmlUnescape(stripped);
	}

	/** Collapse whitespace to single spaces and trim. */
	static String normalizeDocText(String input) {
		return String.join(" ", input.split("\\s+")).trim();
	}

	private static String htmlUnescape(String input) {
		return input.replace("&lt;", "<")
			.replace("&gt;", ">")
			.replace("&amp;", "&")
			.replace("&quot;", "\"")
			.replace("&#39;", "'")
			.replace("&nbsp;", " ");
	}

	private static boolean isJavadocMemberSignature(String text) {
		String stripped = stripLeadingAnnotationLines(text);
		String[] tokens = stripped.trim().split("\\s+");
		if (tokens.length == 0 || tokens[0].isEmpty()) {
			return false;
		}
		String first = tokens[0];
		if (!first.equals("public") && !first.equals("protected") && !first.equals("private")) {
			return false;
		}
		for (String token : tokens) {
			if (token.equals("class") || token.equals("interface") || token.equals("enum")
					|| token.equals("record")) {
				return false;
			}
		}
		return true;
	}

	private static boolean isJavadocTypeSignature(String text) {
		for (String token : text.split("\\s+")) {
			if (token.equals("class") || token.equals("interface") || token.equals("enum")
					|| token.equals("record")) {
				return true;
			}
		}
		return false;
	}

	private static String stripLeadingAnnotationLines(String text) {
		String rest = text.trim();
		while (rest.startsWith("@")) {
			int idx = -1;
			for (int i = 0; i < rest.length(); i++) {
				if (Character.isWhitespace(rest.charAt(i))) {
					idx = i;
					break;
				}
			}
			if (idx < 0) {
				return "";
			}
			rest = rest.substring(idx).trim();
		}
		return rest;
	}

	private static byte[] readAllBytes(InputStream in) throws IOException {
		ByteArrayOutputStream buf = new ByteArrayOutputStream();
		byte[] chunk = new byte[8192];
		int n;
		while ((n = in.read(chunk)) != -1) {
			buf.write(chunk, 0, n);
		}
		return buf.toByteArray();
	}

	/** Internal data holder for a member's javadoc. */
	static class MemberDoc {
		String signature;
		String description;
		List<String[]> parameterDescriptions;
		String returnDescription;
	}
}
