name: Allure Report Publish

on:
  workflow_run:
    workflows: ["ci-build"]
    types:
      - completed

defaults:
  run:
    shell: bash

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      issues: write
      # this is unfortunately needed to be able to write comments on pull requests
      pull-requests: write
    if: github.event.workflow_run.event == 'pull_request' 
    steps:
    - name: Download PR Artifact for ubuntu-latest
      uses: actions/download-artifact@v4
      with:
        run-id: ${{ github.event.workflow_run.id }}
        name: allure-report-ubuntu-latest
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Store PR id as variable
      id: pr
      run: |
        pr=$(<pr-id.txt)
        if ! [[ $pr =~ ^[0-9]+$ ]] ; then
          echo "PR id extracted from pr-id.txt is not a number: $pr"
          exit 1
        fi
        echo "id=${pr}" >> $GITHUB_OUTPUT
        rm -f pr-id.txt
    - name: Publishing to surge for preview
      id: deploy
      run: npx surge@0.23.1 ./ --domain https://jbang-site-ci-pr-${PR_ID}-preview.surge.sh --token ${{ secrets.SURGE_TOKEN }}
      env:
        PR_ID: ${{  steps.pr.outputs.id }}

    - name: Update PR status comment on success
      uses: quarkusio/action-helpers@main
      with:
        action: maintain-one-comment
        github-token: ${{ secrets.GITHUB_TOKEN }}
        pr-number: ${{ steps.pr.outputs.id }}
        body: |
          🎊 Antora ubuntu-latest for ${{ github.sha }} has been successfully uploaded to https://quarkus-site-pr-${{ steps.pr.outputs.id }}-preview.surge.sh

        body-marker: <!-- Preview status comment marker -->
    - name: Update PR status comment on failure
      uses: quarkusio/action-helpers@main
      if: ${{ failure() }}
      with:
        action: maintain-one-comment
        github-token: ${{ secrets.GITHUB_TOKEN }}
        pr-number: ${{ steps.pr.outputs.id }}
        body: |
          😭 Allure report for ubuntu-latest failed to upload.
        body-marker: <!-- Preview status comment marker -->